apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: nifi
  app.kubernetes.io/instance: nifi-abcxzy
  app.kubernetes.io/component: infra

namePrefix: nifi-

resources:
- statefulset.yml
- secret.yml
- service.yml
- ingress.yml

configMapGenerator:
  - name: env-vars
    literals:
      - NIFI_LOG_LEVEL=info
